// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewConsoleRepository creates a new instance of ConsoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsoleRepository {
	mock := &ConsoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConsoleRepository is an autogenerated mock type for the ConsoleRepository type
type ConsoleRepository struct {
	mock.Mock
}

type ConsoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsoleRepository) EXPECT() *ConsoleRepository_Expecter {
	return &ConsoleRepository_Expecter{mock: &_m.Mock}
}

// ThemeGet provides a mock function for the type ConsoleRepository
func (_mock *ConsoleRepository) ThemeGet(ctx context.Context) (io.ReadCloser, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ThemeGet")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (io.ReadCloser, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) io.ReadCloser); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConsoleRepository_ThemeGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeGet'
type ConsoleRepository_ThemeGet_Call struct {
	*mock.Call
}

// ThemeGet is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ConsoleRepository_Expecter) ThemeGet(ctx interface{}) *ConsoleRepository_ThemeGet_Call {
	return &ConsoleRepository_ThemeGet_Call{Call: _e.mock.On("ThemeGet", ctx)}
}

func (_c *ConsoleRepository_ThemeGet_Call) Run(run func(ctx context.Context)) *ConsoleRepository_ThemeGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConsoleRepository_ThemeGet_Call) Return(readCloser io.ReadCloser, err error) *ConsoleRepository_ThemeGet_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *ConsoleRepository_ThemeGet_Call) RunAndReturn(run func(ctx context.Context) (io.ReadCloser, error)) *ConsoleRepository_ThemeGet_Call {
	_c.Call.Return(run)
	return _c
}
