// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// ThemeAdd provides a mock function for the type Repository
func (_mock *Repository) ThemeAdd(ctx context.Context, id string, r io.Reader) error {
	ret := _mock.Called(ctx, id, r)

	if len(ret) == 0 {
		panic("no return value specified for ThemeAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader) error); ok {
		r0 = returnFunc(ctx, id, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_ThemeAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeAdd'
type Repository_ThemeAdd_Call struct {
	*mock.Call
}

// ThemeAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - r io.Reader
func (_e *Repository_Expecter) ThemeAdd(ctx interface{}, id interface{}, r interface{}) *Repository_ThemeAdd_Call {
	return &Repository_ThemeAdd_Call{Call: _e.mock.On("ThemeAdd", ctx, id, r)}
}

func (_c *Repository_ThemeAdd_Call) Run(run func(ctx context.Context, id string, r io.Reader)) *Repository_ThemeAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Repository_ThemeAdd_Call) Return(err error) *Repository_ThemeAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_ThemeAdd_Call) RunAndReturn(run func(ctx context.Context, id string, r io.Reader) error) *Repository_ThemeAdd_Call {
	_c.Call.Return(run)
	return _c
}

// ThemeExists provides a mock function for the type Repository
func (_mock *Repository) ThemeExists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ThemeExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_ThemeExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeExists'
type Repository_ThemeExists_Call struct {
	*mock.Call
}

// ThemeExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) ThemeExists(ctx interface{}, id interface{}) *Repository_ThemeExists_Call {
	return &Repository_ThemeExists_Call{Call: _e.mock.On("ThemeExists", ctx, id)}
}

func (_c *Repository_ThemeExists_Call) Run(run func(ctx context.Context, id string)) *Repository_ThemeExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ThemeExists_Call) Return(b bool, err error) *Repository_ThemeExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Repository_ThemeExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *Repository_ThemeExists_Call {
	_c.Call.Return(run)
	return _c
}

// ThemeRemove provides a mock function for the type Repository
func (_mock *Repository) ThemeRemove(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ThemeRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_ThemeRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeRemove'
type Repository_ThemeRemove_Call struct {
	*mock.Call
}

// ThemeRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *Repository_Expecter) ThemeRemove(ctx interface{}, id interface{}) *Repository_ThemeRemove_Call {
	return &Repository_ThemeRemove_Call{Call: _e.mock.On("ThemeRemove", ctx, id)}
}

func (_c *Repository_ThemeRemove_Call) Run(run func(ctx context.Context, id string)) *Repository_ThemeRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_ThemeRemove_Call) Return(err error) *Repository_ThemeRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_ThemeRemove_Call) RunAndReturn(run func(ctx context.Context, id string) error) *Repository_ThemeRemove_Call {
	_c.Call.Return(run)
	return _c
}
