// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ThemeApply provides a mock function for the type Service
func (_mock *Service) ThemeApply(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ThemeApply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ThemeApply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeApply'
type Service_ThemeApply_Call struct {
	*mock.Call
}

// ThemeApply is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Service_Expecter) ThemeApply(context1 interface{}) *Service_ThemeApply_Call {
	return &Service_ThemeApply_Call{Call: _e.mock.On("ThemeApply", context1)}
}

func (_c *Service_ThemeApply_Call) Run(run func(context1 context.Context)) *Service_ThemeApply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_ThemeApply_Call) Return(err error) *Service_ThemeApply_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ThemeApply_Call) RunAndReturn(run func(context1 context.Context) error) *Service_ThemeApply_Call {
	_c.Call.Return(run)
	return _c
}

// ThemeRemove provides a mock function for the type Service
func (_mock *Service) ThemeRemove(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ThemeRemove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_ThemeRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThemeRemove'
type Service_ThemeRemove_Call struct {
	*mock.Call
}

// ThemeRemove is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Service_Expecter) ThemeRemove(context1 interface{}) *Service_ThemeRemove_Call {
	return &Service_ThemeRemove_Call{Call: _e.mock.On("ThemeRemove", context1)}
}

func (_c *Service_ThemeRemove_Call) Run(run func(context1 context.Context)) *Service_ThemeRemove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_ThemeRemove_Call) Return(err error) *Service_ThemeRemove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_ThemeRemove_Call) RunAndReturn(run func(context1 context.Context) error) *Service_ThemeRemove_Call {
	_c.Call.Return(run)
	return _c
}
