package config

import (
	"context"

	"github.com/opencloud-eu/opencloud/pkg/shared"
)

// Config combines all available configuration parts for the auth-authelia service.
//
// The auth-authelia service embeds Authelia (https://www.authelia.com) as an out-of-the-box
// authentication provider and OpenID Connect provider. Unlike most other OpenCloud services it
// does not expose a go-micro HTTP server. Instead it boots Authelia via the upstream
// experimental/embed package, which serves its own HTTP listener. The OpenCloud proxy forwards
// the relevant request paths to that listener.
//
// The actual Authelia configuration (LDAP backend, OIDC clients, storage, notifier, secrets) lives
// in a dedicated YAML file. Mirroring how the idp (lico) service generates its clients registration
// config, the auth-authelia service renders that file itself on first start (see pkg/render); it is
// not produced by `opencloud init`. This service only needs to know where the file lives and the
// shared 'authelia' LDAP bind password.
type Config struct {
	Commons *shared.Commons `yaml:"-"` // don't use this directly as configuration for a service

	Service Service `yaml:"-"`

	LogLevel string `yaml:"loglevel" env:"OC_LOG_LEVEL;AUTH_AUTHELIA_LOG_LEVEL" desc:"The log level. Valid values are: 'panic', 'fatal', 'error', 'warn', 'info', 'debug', 'trace'." introductionVersion:"7.0.0"`

	ConfigPath  string   `yaml:"config_path" env:"AUTH_AUTHELIA_CONFIG_PATH" desc:"Path to the Authelia configuration file. The auth-authelia service renders it on first start if it does not exist." introductionVersion:"7.0.0"`
	FilterNames []string `yaml:"-"` // Authelia config file filters (e.g. 'template'); empty by default.

	LDAP LDAP `yaml:"ldap"`
	SMTP SMTP `yaml:"smtp"`

	Context context.Context `yaml:"-"`
}

// SMTP configures the Authelia mail notifier (password reset, 2FA registration). It is optional:
// when Host is empty the service renders a filesystem notifier instead, so a fresh deployment works
// without any mail server. The env vars default to the OpenCloud notifications service's SMTP
// settings (so SMTP is configured once for the whole deployment), with AUTH_AUTHELIA_SMTP_* taking
// precedence when an Authelia-specific mail server is wanted.
type SMTP struct {
	Host       string `yaml:"smtp_host" env:"NOTIFICATIONS_SMTP_HOST;AUTH_AUTHELIA_SMTP_HOST" desc:"SMTP host to connect to. When set, Authelia sends notification mails via SMTP; when empty it writes them to a file." introductionVersion:"7.0.0"`
	Port       int    `yaml:"smtp_port" env:"NOTIFICATIONS_SMTP_PORT;AUTH_AUTHELIA_SMTP_PORT" desc:"Port of the SMTP host to connect to." introductionVersion:"7.0.0"`
	Sender     string `yaml:"smtp_sender" env:"NOTIFICATIONS_SMTP_SENDER;AUTH_AUTHELIA_SMTP_SENDER" desc:"Sender address of emails sent by Authelia (e.g. 'OpenCloud <noreply@example.com>')." introductionVersion:"7.0.0"`
	Username   string `yaml:"smtp_username" env:"NOTIFICATIONS_SMTP_USERNAME;AUTH_AUTHELIA_SMTP_USERNAME" desc:"Username for SMTP authentication." introductionVersion:"7.0.0"`
	Password   string `yaml:"smtp_password" env:"NOTIFICATIONS_SMTP_PASSWORD;AUTH_AUTHELIA_SMTP_PASSWORD" desc:"Password for SMTP authentication." introductionVersion:"7.0.0"`
	Encryption string `yaml:"smtp_encryption" env:"NOTIFICATIONS_SMTP_ENCRYPTION;AUTH_AUTHELIA_SMTP_ENCRYPTION" desc:"Encryption method for SMTP. Possible values are 'starttls', 'ssltls' and 'none'." introductionVersion:"7.0.0"`
}

// LDAP holds the settings the service needs to render the Authelia LDAP authentication backend.
// Authelia binds to the embedded libregraph-idm directory as the idm admin user (uid=libregraph) -
// the only account the directory lets modify entries, which Authelia needs for password changes.
// Only the bind password is configurable here; the bind DN and address are fixed to the embedded
// directory.
type LDAP struct {
	BindPassword string `yaml:"bind_password" env:"OC_LDAP_BIND_PASSWORD;AUTH_AUTHELIA_LDAP_BIND_PASSWORD" desc:"Password for the 'idm' admin LDAP user (uid=libregraph) Authelia binds as. Generated by 'opencloud init' (shared with the idm service)." introductionVersion:"7.0.0"`
}

// Service defines the available service configuration.
type Service struct {
	Name string `yaml:"-"`
}
