// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/cs3org/go-cs3apis/cs3/sharing/collaboration/v1beta1"
	"github.com/cs3org/go-cs3apis/cs3/sharing/ocm/v1beta1"
	"github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1"
	"github.com/opencloud-eu/opencloud/services/graph/pkg/service/v0"
	mock "github.com/stretchr/testify/mock"
)

// NewDrivesDriveItemProvider creates a new instance of DrivesDriveItemProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDrivesDriveItemProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DrivesDriveItemProvider {
	mock := &DrivesDriveItemProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DrivesDriveItemProvider is an autogenerated mock type for the DrivesDriveItemProvider type
type DrivesDriveItemProvider struct {
	mock.Mock
}

type DrivesDriveItemProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *DrivesDriveItemProvider) EXPECT() *DrivesDriveItemProvider_Expecter {
	return &DrivesDriveItemProvider_Expecter{mock: &_m.Mock}
}

// CreateChild provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) CreateChild(ctx context.Context, parentID *providerv1beta1.ResourceId, name string, isFolder bool, replace bool) (*providerv1beta1.ResourceInfo, error) {
	ret := _mock.Called(ctx, parentID, name, isFolder, replace)

	if len(ret) == 0 {
		panic("no return value specified for CreateChild")
	}

	var r0 *providerv1beta1.ResourceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string, bool, bool) (*providerv1beta1.ResourceInfo, error)); ok {
		return returnFunc(ctx, parentID, name, isFolder, replace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string, bool, bool) *providerv1beta1.ResourceInfo); ok {
		r0 = returnFunc(ctx, parentID, name, isFolder, replace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerv1beta1.ResourceInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *providerv1beta1.ResourceId, string, bool, bool) error); ok {
		r1 = returnFunc(ctx, parentID, name, isFolder, replace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_CreateChild_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChild'
type DrivesDriveItemProvider_CreateChild_Call struct {
	*mock.Call
}

// CreateChild is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *providerv1beta1.ResourceId
//   - name string
//   - isFolder bool
//   - replace bool
func (_e *DrivesDriveItemProvider_Expecter) CreateChild(ctx interface{}, parentID interface{}, name interface{}, isFolder interface{}, replace interface{}) *DrivesDriveItemProvider_CreateChild_Call {
	return &DrivesDriveItemProvider_CreateChild_Call{Call: _e.mock.On("CreateChild", ctx, parentID, name, isFolder, replace)}
}

func (_c *DrivesDriveItemProvider_CreateChild_Call) Run(run func(ctx context.Context, parentID *providerv1beta1.ResourceId, name string, isFolder bool, replace bool)) *DrivesDriveItemProvider_CreateChild_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providerv1beta1.ResourceId
		if args[1] != nil {
			arg1 = args[1].(*providerv1beta1.ResourceId)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_CreateChild_Call) Return(resourceInfo *providerv1beta1.ResourceInfo, err error) *DrivesDriveItemProvider_CreateChild_Call {
	_c.Call.Return(resourceInfo, err)
	return _c
}

func (_c *DrivesDriveItemProvider_CreateChild_Call) RunAndReturn(run func(ctx context.Context, parentID *providerv1beta1.ResourceId, name string, isFolder bool, replace bool) (*providerv1beta1.ResourceInfo, error)) *DrivesDriveItemProvider_CreateChild_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePath provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) CreatePath(ctx context.Context, parentID *providerv1beta1.ResourceId, relPath string) (*providerv1beta1.ResourceId, error) {
	ret := _mock.Called(ctx, parentID, relPath)

	if len(ret) == 0 {
		panic("no return value specified for CreatePath")
	}

	var r0 *providerv1beta1.ResourceId
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string) (*providerv1beta1.ResourceId, error)); ok {
		return returnFunc(ctx, parentID, relPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string) *providerv1beta1.ResourceId); ok {
		r0 = returnFunc(ctx, parentID, relPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerv1beta1.ResourceId)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *providerv1beta1.ResourceId, string) error); ok {
		r1 = returnFunc(ctx, parentID, relPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_CreatePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePath'
type DrivesDriveItemProvider_CreatePath_Call struct {
	*mock.Call
}

// CreatePath is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID *providerv1beta1.ResourceId
//   - relPath string
func (_e *DrivesDriveItemProvider_Expecter) CreatePath(ctx interface{}, parentID interface{}, relPath interface{}) *DrivesDriveItemProvider_CreatePath_Call {
	return &DrivesDriveItemProvider_CreatePath_Call{Call: _e.mock.On("CreatePath", ctx, parentID, relPath)}
}

func (_c *DrivesDriveItemProvider_CreatePath_Call) Run(run func(ctx context.Context, parentID *providerv1beta1.ResourceId, relPath string)) *DrivesDriveItemProvider_CreatePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providerv1beta1.ResourceId
		if args[1] != nil {
			arg1 = args[1].(*providerv1beta1.ResourceId)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_CreatePath_Call) Return(resourceId *providerv1beta1.ResourceId, err error) *DrivesDriveItemProvider_CreatePath_Call {
	_c.Call.Return(resourceId, err)
	return _c
}

func (_c *DrivesDriveItemProvider_CreatePath_Call) RunAndReturn(run func(ctx context.Context, parentID *providerv1beta1.ResourceId, relPath string) (*providerv1beta1.ResourceId, error)) *DrivesDriveItemProvider_CreatePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetShare provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) GetShare(ctx context.Context, shareID *collaborationv1beta1.ShareId) (*collaborationv1beta1.ReceivedShare, error) {
	ret := _mock.Called(ctx, shareID)

	if len(ret) == 0 {
		panic("no return value specified for GetShare")
	}

	var r0 *collaborationv1beta1.ReceivedShare
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *collaborationv1beta1.ShareId) (*collaborationv1beta1.ReceivedShare, error)); ok {
		return returnFunc(ctx, shareID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *collaborationv1beta1.ShareId) *collaborationv1beta1.ReceivedShare); ok {
		r0 = returnFunc(ctx, shareID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*collaborationv1beta1.ReceivedShare)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *collaborationv1beta1.ShareId) error); ok {
		r1 = returnFunc(ctx, shareID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_GetShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShare'
type DrivesDriveItemProvider_GetShare_Call struct {
	*mock.Call
}

// GetShare is a helper method to define mock.On call
//   - ctx context.Context
//   - shareID *collaborationv1beta1.ShareId
func (_e *DrivesDriveItemProvider_Expecter) GetShare(ctx interface{}, shareID interface{}) *DrivesDriveItemProvider_GetShare_Call {
	return &DrivesDriveItemProvider_GetShare_Call{Call: _e.mock.On("GetShare", ctx, shareID)}
}

func (_c *DrivesDriveItemProvider_GetShare_Call) Run(run func(ctx context.Context, shareID *collaborationv1beta1.ShareId)) *DrivesDriveItemProvider_GetShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *collaborationv1beta1.ShareId
		if args[1] != nil {
			arg1 = args[1].(*collaborationv1beta1.ShareId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_GetShare_Call) Return(receivedShare *collaborationv1beta1.ReceivedShare, err error) *DrivesDriveItemProvider_GetShare_Call {
	_c.Call.Return(receivedShare, err)
	return _c
}

func (_c *DrivesDriveItemProvider_GetShare_Call) RunAndReturn(run func(ctx context.Context, shareID *collaborationv1beta1.ShareId) (*collaborationv1beta1.ReceivedShare, error)) *DrivesDriveItemProvider_GetShare_Call {
	_c.Call.Return(run)
	return _c
}

// GetSharesForResource provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) GetSharesForResource(ctx context.Context, resourceID *providerv1beta1.ResourceId, filters []*collaborationv1beta1.Filter) ([]*collaborationv1beta1.ReceivedShare, error) {
	ret := _mock.Called(ctx, resourceID, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetSharesForResource")
	}

	var r0 []*collaborationv1beta1.ReceivedShare
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, []*collaborationv1beta1.Filter) ([]*collaborationv1beta1.ReceivedShare, error)); ok {
		return returnFunc(ctx, resourceID, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, []*collaborationv1beta1.Filter) []*collaborationv1beta1.ReceivedShare); ok {
		r0 = returnFunc(ctx, resourceID, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*collaborationv1beta1.ReceivedShare)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *providerv1beta1.ResourceId, []*collaborationv1beta1.Filter) error); ok {
		r1 = returnFunc(ctx, resourceID, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_GetSharesForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSharesForResource'
type DrivesDriveItemProvider_GetSharesForResource_Call struct {
	*mock.Call
}

// GetSharesForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID *providerv1beta1.ResourceId
//   - filters []*collaborationv1beta1.Filter
func (_e *DrivesDriveItemProvider_Expecter) GetSharesForResource(ctx interface{}, resourceID interface{}, filters interface{}) *DrivesDriveItemProvider_GetSharesForResource_Call {
	return &DrivesDriveItemProvider_GetSharesForResource_Call{Call: _e.mock.On("GetSharesForResource", ctx, resourceID, filters)}
}

func (_c *DrivesDriveItemProvider_GetSharesForResource_Call) Run(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId, filters []*collaborationv1beta1.Filter)) *DrivesDriveItemProvider_GetSharesForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providerv1beta1.ResourceId
		if args[1] != nil {
			arg1 = args[1].(*providerv1beta1.ResourceId)
		}
		var arg2 []*collaborationv1beta1.Filter
		if args[2] != nil {
			arg2 = args[2].([]*collaborationv1beta1.Filter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_GetSharesForResource_Call) Return(receivedShares []*collaborationv1beta1.ReceivedShare, err error) *DrivesDriveItemProvider_GetSharesForResource_Call {
	_c.Call.Return(receivedShares, err)
	return _c
}

func (_c *DrivesDriveItemProvider_GetSharesForResource_Call) RunAndReturn(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId, filters []*collaborationv1beta1.Filter) ([]*collaborationv1beta1.ReceivedShare, error)) *DrivesDriveItemProvider_GetSharesForResource_Call {
	_c.Call.Return(run)
	return _c
}

// MountOCMShare provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) MountOCMShare(ctx context.Context, resourceID *providerv1beta1.ResourceId) ([]*ocmv1beta1.ReceivedShare, error) {
	ret := _mock.Called(ctx, resourceID)

	if len(ret) == 0 {
		panic("no return value specified for MountOCMShare")
	}

	var r0 []*ocmv1beta1.ReceivedShare
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId) ([]*ocmv1beta1.ReceivedShare, error)); ok {
		return returnFunc(ctx, resourceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId) []*ocmv1beta1.ReceivedShare); ok {
		r0 = returnFunc(ctx, resourceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ocmv1beta1.ReceivedShare)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *providerv1beta1.ResourceId) error); ok {
		r1 = returnFunc(ctx, resourceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_MountOCMShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MountOCMShare'
type DrivesDriveItemProvider_MountOCMShare_Call struct {
	*mock.Call
}

// MountOCMShare is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID *providerv1beta1.ResourceId
func (_e *DrivesDriveItemProvider_Expecter) MountOCMShare(ctx interface{}, resourceID interface{}) *DrivesDriveItemProvider_MountOCMShare_Call {
	return &DrivesDriveItemProvider_MountOCMShare_Call{Call: _e.mock.On("MountOCMShare", ctx, resourceID)}
}

func (_c *DrivesDriveItemProvider_MountOCMShare_Call) Run(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId)) *DrivesDriveItemProvider_MountOCMShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providerv1beta1.ResourceId
		if args[1] != nil {
			arg1 = args[1].(*providerv1beta1.ResourceId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_MountOCMShare_Call) Return(receivedShares []*ocmv1beta1.ReceivedShare, err error) *DrivesDriveItemProvider_MountOCMShare_Call {
	_c.Call.Return(receivedShares, err)
	return _c
}

func (_c *DrivesDriveItemProvider_MountOCMShare_Call) RunAndReturn(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId) ([]*ocmv1beta1.ReceivedShare, error)) *DrivesDriveItemProvider_MountOCMShare_Call {
	_c.Call.Return(run)
	return _c
}

// MountShare provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) MountShare(ctx context.Context, resourceID *providerv1beta1.ResourceId, name string) ([]*collaborationv1beta1.ReceivedShare, error) {
	ret := _mock.Called(ctx, resourceID, name)

	if len(ret) == 0 {
		panic("no return value specified for MountShare")
	}

	var r0 []*collaborationv1beta1.ReceivedShare
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string) ([]*collaborationv1beta1.ReceivedShare, error)); ok {
		return returnFunc(ctx, resourceID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *providerv1beta1.ResourceId, string) []*collaborationv1beta1.ReceivedShare); ok {
		r0 = returnFunc(ctx, resourceID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*collaborationv1beta1.ReceivedShare)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *providerv1beta1.ResourceId, string) error); ok {
		r1 = returnFunc(ctx, resourceID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_MountShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MountShare'
type DrivesDriveItemProvider_MountShare_Call struct {
	*mock.Call
}

// MountShare is a helper method to define mock.On call
//   - ctx context.Context
//   - resourceID *providerv1beta1.ResourceId
//   - name string
func (_e *DrivesDriveItemProvider_Expecter) MountShare(ctx interface{}, resourceID interface{}, name interface{}) *DrivesDriveItemProvider_MountShare_Call {
	return &DrivesDriveItemProvider_MountShare_Call{Call: _e.mock.On("MountShare", ctx, resourceID, name)}
}

func (_c *DrivesDriveItemProvider_MountShare_Call) Run(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId, name string)) *DrivesDriveItemProvider_MountShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *providerv1beta1.ResourceId
		if args[1] != nil {
			arg1 = args[1].(*providerv1beta1.ResourceId)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_MountShare_Call) Return(receivedShares []*collaborationv1beta1.ReceivedShare, err error) *DrivesDriveItemProvider_MountShare_Call {
	_c.Call.Return(receivedShares, err)
	return _c
}

func (_c *DrivesDriveItemProvider_MountShare_Call) RunAndReturn(run func(ctx context.Context, resourceID *providerv1beta1.ResourceId, name string) ([]*collaborationv1beta1.ReceivedShare, error)) *DrivesDriveItemProvider_MountShare_Call {
	_c.Call.Return(run)
	return _c
}

// UnmountShare provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) UnmountShare(ctx context.Context, shareID *collaborationv1beta1.ShareId) error {
	ret := _mock.Called(ctx, shareID)

	if len(ret) == 0 {
		panic("no return value specified for UnmountShare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *collaborationv1beta1.ShareId) error); ok {
		r0 = returnFunc(ctx, shareID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DrivesDriveItemProvider_UnmountShare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnmountShare'
type DrivesDriveItemProvider_UnmountShare_Call struct {
	*mock.Call
}

// UnmountShare is a helper method to define mock.On call
//   - ctx context.Context
//   - shareID *collaborationv1beta1.ShareId
func (_e *DrivesDriveItemProvider_Expecter) UnmountShare(ctx interface{}, shareID interface{}) *DrivesDriveItemProvider_UnmountShare_Call {
	return &DrivesDriveItemProvider_UnmountShare_Call{Call: _e.mock.On("UnmountShare", ctx, shareID)}
}

func (_c *DrivesDriveItemProvider_UnmountShare_Call) Run(run func(ctx context.Context, shareID *collaborationv1beta1.ShareId)) *DrivesDriveItemProvider_UnmountShare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *collaborationv1beta1.ShareId
		if args[1] != nil {
			arg1 = args[1].(*collaborationv1beta1.ShareId)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_UnmountShare_Call) Return(err error) *DrivesDriveItemProvider_UnmountShare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DrivesDriveItemProvider_UnmountShare_Call) RunAndReturn(run func(ctx context.Context, shareID *collaborationv1beta1.ShareId) error) *DrivesDriveItemProvider_UnmountShare_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateShares provides a mock function for the type DrivesDriveItemProvider
func (_mock *DrivesDriveItemProvider) UpdateShares(ctx context.Context, shares []*collaborationv1beta1.ReceivedShare, updater svc.UpdateShareClosure) ([]*collaborationv1beta1.ReceivedShare, error) {
	ret := _mock.Called(ctx, shares, updater)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShares")
	}

	var r0 []*collaborationv1beta1.ReceivedShare
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*collaborationv1beta1.ReceivedShare, svc.UpdateShareClosure) ([]*collaborationv1beta1.ReceivedShare, error)); ok {
		return returnFunc(ctx, shares, updater)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*collaborationv1beta1.ReceivedShare, svc.UpdateShareClosure) []*collaborationv1beta1.ReceivedShare); ok {
		r0 = returnFunc(ctx, shares, updater)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*collaborationv1beta1.ReceivedShare)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []*collaborationv1beta1.ReceivedShare, svc.UpdateShareClosure) error); ok {
		r1 = returnFunc(ctx, shares, updater)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DrivesDriveItemProvider_UpdateShares_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateShares'
type DrivesDriveItemProvider_UpdateShares_Call struct {
	*mock.Call
}

// UpdateShares is a helper method to define mock.On call
//   - ctx context.Context
//   - shares []*collaborationv1beta1.ReceivedShare
//   - updater svc.UpdateShareClosure
func (_e *DrivesDriveItemProvider_Expecter) UpdateShares(ctx interface{}, shares interface{}, updater interface{}) *DrivesDriveItemProvider_UpdateShares_Call {
	return &DrivesDriveItemProvider_UpdateShares_Call{Call: _e.mock.On("UpdateShares", ctx, shares, updater)}
}

func (_c *DrivesDriveItemProvider_UpdateShares_Call) Run(run func(ctx context.Context, shares []*collaborationv1beta1.ReceivedShare, updater svc.UpdateShareClosure)) *DrivesDriveItemProvider_UpdateShares_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*collaborationv1beta1.ReceivedShare
		if args[1] != nil {
			arg1 = args[1].([]*collaborationv1beta1.ReceivedShare)
		}
		var arg2 svc.UpdateShareClosure
		if args[2] != nil {
			arg2 = args[2].(svc.UpdateShareClosure)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DrivesDriveItemProvider_UpdateShares_Call) Return(receivedShares []*collaborationv1beta1.ReceivedShare, err error) *DrivesDriveItemProvider_UpdateShares_Call {
	_c.Call.Return(receivedShares, err)
	return _c
}

func (_c *DrivesDriveItemProvider_UpdateShares_Call) RunAndReturn(run func(ctx context.Context, shares []*collaborationv1beta1.ReceivedShare, updater svc.UpdateShareClosure) ([]*collaborationv1beta1.ReceivedShare, error)) *DrivesDriveItemProvider_UpdateShares_Call {
	_c.Call.Return(run)
	return _c
}
